**22-01-2026** - ***tokenization and embeddings (2 ways of tokenization, 2 ways of embeddings (word2vec) compulsory Single head attention multi head attention***

***1A — Tokenization***



*A. WHITE SPACE*

In [ ]:
text = "dream big and work for it"
tokens = text.split()
print(tokens)


['dream', 'big', 'and', 'work', 'for', 'it']


*B. Character-Level*

In [ ]:
text = "dream big"
tokens = list(text.replace(" ", ""))
print(tokens)


['d', 'r', 'e', 'a', 'm', 'b', 'i', 'g']


*C. Subword NLP *

In [ ]:
from transformers import BertTokenizer

text = "Dreaming big and working hard leads to success"
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
tokens = tokenizer.tokenize(text)
print(tokens)


['dreaming', 'big', 'and', 'working', 'hard', 'leads', 'to', 'success']


*D. Subword Tokenization (NLP Library: BERT WordPiece)*

In [ ]:
from transformers import BertTokenizer

text = "Dreaming big and working hard leads to success"
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
tokens = tokenizer.tokenize(text)
print(tokens)


['dreaming', 'big', 'and', 'working', 'hard', 'leads', 'to', 'success']


*E. Stopword Removal (NLP Library: NLTK)*

In [ ]:
import nltk
from nltk.corpus import stopwords

nltk.download("stopwords")

text = "Dreaming big and working hard leads to success"
words = text.lower().split()
stops = set(stopwords.words("english"))
filtered = [w for w in words if w not in stops]
print(filtered)


['dreaming', 'big', 'working', 'hard', 'leads', 'success']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


*2A - EMBEDDINGS*

*1 — One-Hot Encoding (One Word Representation)*

In [ ]:
import numpy as np

words = ["dream", "big", "work"]
vocab = {w:i for i,w in enumerate(words)}
vector = np.zeros(len(words))
vector[vocab["dream"]] = 1
print(vector)


[1. 0. 0.]


*2 — Bag of Words*

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

texts = ["dream big", "dream work"]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)
print(X.toarray())
print(vectorizer.get_feature_names_out())


[[1 1 0]
 [0 1 1]]
['big' 'dream' 'work']


*3 — Word2Vec*

In [ ]:
import sys
!{sys.executable} -m pip install gensim
from gensim.models import Word2Vec

sentences = [["dream", "big", "work"], ["work", "hard", "dream"]]
model = Word2Vec(sentences, vector_size=5, window=2, min_count=1, sg=1)
print(model.wv["dream"])

[-0.14233617  0.12917745  0.17945977 -0.10030856 -0.07526743]


*4 — GloVe*

In [ ]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove.6B.zip

from gensim.models import KeyedVectors

model = KeyedVectors.load_word2vec_format("glove.6B.50d.txt", binary=False, no_header=True)
print(model["dream"])

--2026-01-22 10:20:21--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2026-01-22 10:20:21--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2026-01-22 10:20:21--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip.1’

gl

*5 — BERT Embedding*

In [ ]:
import torch
from transformers import BertTokenizer, BertModel

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")

inputs = tokenizer("dream big", return_tensors="pt")
outputs = model(**inputs)
print(outputs.last_hidden_state)


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

tensor([[[-0.3044,  0.0246, -0.0854,  ..., -0.4167, -0.0555,  0.0712],
         [-0.3042, -0.4237,  0.8471,  ..., -0.4764, -0.1558, -0.5731],
         [-0.2668, -0.5213,  0.5794,  ..., -0.2308,  0.1736, -0.5667],
         [ 0.8443,  0.0053, -0.2142,  ...,  0.0654, -0.7880, -0.2874]]],
       grad_fn=<NativeLayerNormBackward0>)
